export const SIGN_UP_URL = 'http://localhost:4000/api/auth/register'
export const LOG_IN_URL = 'http://localhost:4000/api/auth/login'
export const PROFILE_URL = 'http://localhost:4000/api/auth'
export const GET_ALL_STOCKS = 'https://financialmodelingprep.com/api/v3/stock/list'
export const ADD_STOCK_URL = 'http://localhost:4000/api/stock'
export const GET_COMPANY_NAMES = 'https://financialmodelingprep.com/api/v3/quote/'
export const API_KEY = '?apikey=ec17cf42b20e533904666651c8f5af41'
