export const SIGN_UP_URL = 'http://localhost:4000/api/auth/register'
export const LOG_IN_URL = 'http://localhost:4000/api/auth/login'
export const PROFILE_URL = 'http://localhost:4000/api/auth'
export const GET_ALL_STOCKS = 'https://financialmodelingprep.com/api/v3/stock/list?apikey=3b078f5a35f426d735a517bc847f7be4'
export const ADD_STOCK_URL = 'http://localhost:4000/api/stock'