export const SAVE_NEWUSER = 'SAVE_NEWUSER'
export const WRITE_ERROR = 'WRITE_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
export const ADD_STOCK = 'ADD_STOCK'
